version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    # Optional labels to help triage Dependabot PRs
    labels:
      - "dependencies"
      - "bot"
    # Rebase stale PRs automatically so they stay up-to-date
    rebase-strategy: "auto"
